config/routes.rb
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
Rails.application.routes.draw do

  root to:"main#index"

  # for authentication
  get "sign-up", to: "registration#new"
  post "sign-up", to: "registration#create"

  delete "logout", to: "session#destroy"
  get "sign-in", to: "session#new"
  post "sign-in", to: "session#create"

  # change password
  get "password", to: "password#edit", as: :edit_password
  patch "password", to: "password#update", as: :update_password

  # password reset
  get "password/reset", to: "password_reset#new"
  post "password/reset", to: "password_reset#create"

  # for about page
  get "about", to: "about#index"
  # for features page
  get "features", to: "features#index"
  # for faq page
  get "faq", to: "faq#index"
  # for pricing page
  get "pricing", to: "pricing#index"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/current.rb
class Current < ActiveSupport::CurrentAttributes
  attribute :user
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    validates_uniqueness_of :email
    validates_format_of :email, with: URI::MailTo::EMAIL_REGEXP,
                                message: "must be a valid email address"
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
  def index

  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  before_action :set_current_user

  def set_current_user
    if session[:user_id]
      Current.user = User.find(session[:user_id])
    end
  end

  def require_user_logged_in
    redirect_to sign_in_path, alert: "You mus be signed in to do that." if Current.user.nil?
  end

end

app/controllers/faq_controller.rb
class FaqController < ApplicationController
  def index

  end
end

app/controllers/features_controller.rb
class FeaturesController < ApplicationController
  def index

  end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
    # flash[:notice] = "Logged in succesfully"
    # flash[:alert] = "Invalid email or password"
  end
end

app/controllers/password_controller.rb
class PasswordController < ApplicationController

  before_action :require_user_logged_in

  def edit

  end

  def update
    if Current.user.update(password_params)
      redirect_to root_path, notice: "Password updated successfully"
    else
      render :edit
    end
  end

  private

  def password_params
    params.required(:user).permit(:password, :password_confirmation)
  end
end

app/controllers/pricing_controller.rb
class PricingController < ApplicationController
  def index

  end
end

app/controllers/registration_controller.rb
class RegistrationController < ApplicationController
    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)
        if @user.save
            session[:user_id] = @user.id
            redirect_to root_path, notice:"Successfully created account"
        else
            render :new
        end
    end

    private

    def user_params
        params.require(:user).permit(:email, :password, :password_confirmation)
    end

end

app/controllers/session_controller.rb
class SessionController < ApplicationController

  def new

  end

  def create
    user = User.find_by(email: params[:email])
    if user.present? && user.authenticate(params[:password])
      session[:user_id] = user.id
      redirect_to root_path, notice: "Logged in succesfully"
    else
      flash[:alert] = "Invalid email and password"
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: "Logged Out"
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/about/index.html.erb
<h1>About</h1>
<p>This is about page</p>

app/views/faq/index.html.erb
<h1>FAQ's</h1>
<p>This is FAQ's page</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>PostScheduleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
  <body>
    <header>
      <%= render "layouts/nav/navbar" %>
    </header>
    <div class="container">
      <%= render partial:"shared/flash" %>
      <%= yield %>
    </div>
    <footer>
      <%= render partial:"layouts/footer/footer" %>
    </footer>
  </body>
</html>

app/views/layouts/footer/_footer.html.erb
<div class="container-fluid pt-3">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-muted">&copy; 2021 Diposting, Inc</p>
    <ul class="nav col-md-4 justify-content-end">
      <%= link_to "Home", root_path, class: "nav-link px-2 text-muted" %>
      <%= link_to "Features", features_path, class: "nav-link px-2 text-muted" %>
      <%= link_to "Pricing", pricing_path, class: "nav-link px-2 text-muted" %>
      <%= link_to "FAQ's", faq_path, class: "nav-link px-2 text-muted" %>
      <%= link_to "About", about_path, class: "nav-link px-2 text-muted" %>
    </ul>
  </footer>
</div>

app/views/layouts/nav/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light" id="main-navbar">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">
      <img src="<%= asset_url "logo-width.png" %>" alt="" width="165" height="55"></img>
  </a>
  <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav">
      <li class="nav-item">
        <a class="nav-link fs-5" aria-current="page" href="/">Home</a>
      </li>
      <li class="nav-item">
        <%= link_to "Features", features_path, class: "nav-link fs-5" %>
      </li>
      <li class="nav-item">
        <%= link_to "Pricing", pricing_path, class: "nav-link fs-5" %>
      </li>
      <li class="nav-item">
        <%= link_to "FAQ's", faq_path, class: "nav-link fs-5" %>
      </li>
      <li class="nav-item">
        <%= link_to "About", about_path, class: "nav-link fs-5" %>
      </li>
    </ul>
    <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
      <% if Current.user %>
        <!-- <li class="nav-item nav-link fs-5"></li> -->
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle fs-5" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Hai, <%= Current.user.email %>
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Profile</a></li>
            <li><%= link_to "Change Password", edit_password_path, class: "dropdown-item"%></li>
            <li><hr class="dropdown-divider"></li>
            <li><%= link_to "Logout", logout_path, class: "dropdown-item", method: :delete %></li>
          </ul>
        </li>
      <% else %>
        <%= link_to "Get started now", sign_up_path, class: "btn btn-primary btn-lg me-3" %>
        <%= link_to "Log in", sign_in_path, class: "btn btn-outline-primary btn-lg", id:"btn-login" %>
      <% end %>
    </ul>
  </div>
</div>
</nav>

app/views/main/index.html.erb
<div class="col md-12 pt-5 text-center">
  <h1>Welcome to PostScheduleApp</h1>
</div>

app/views/password/edit.html.erb
<div class="col-md-8 offset-md-2 mt-5">
  <img class="mx-auto d-block mb-2" id="logo" src="<%= asset_url "logo.png" %>" alt="" width="72" height="72">
  <h1 class="h1 text-md-center">Change your password</h1>
  <%= form_with model: Current.user, url: edit_password_path do |form| %>
    <% if form.object.errors.any? %>
      <div class="alert alert-danger">
        <% form.object.errors.full_messages.each do |message| %>
          <div>
            <%= message %>
          </div>
        <% end %>
      </div>
    <% end %>
    <div class="mb-3">
      <%=form.label :password, class: "form-label" %>
      <%= form.password_field :password, class: "form-control", required: "true", placeholder: "Your password" %>
    </div>
    <div class="mb-3">
      <%= form.label :password_confirmation, class: "form-label" %>
      <%= form.password_field :password_confirmation, class: "form-control", required: "true", placeholder: "Confirm your password" %>
    </div>
    <%= form.submit "Update Password", class: "w-100 btn btn-lg btn-primary" %>
  <% end %>
</div>

app/views/pricing/index.html.erb
<h1>Pricing</h1>
<p>This is pricing page</p>

app/views/session/new.html.erb
<div class="col-md-4 offset-md-4 mt-5">
  <img class="mx-auto d-block mb-2" id="logo" src="<%= asset_url "logo.png" %>" alt="" width="72" height="72">
  <h1 class="h1 text-md-center">Sign In</h1>
  <%= form_with url: sign_in_path do |form| %>
    <div class="mb-3">
      <%=form.label :email, class: "form-label" %>
      <%= form.text_field :email, class: "form-control", required: "true", placeholder: "Your email" %>
    </div>
    <div class="mb-3">
      <%=form.label :password, class: "form-label" %>
      <%= form.password_field :password, class: "form-control", required: "true", placeholder: "Your password" %>
    </div>
    <%= form.submit "Sign In", class: "w-100 btn btn-lg btn-primary" %>
  <% end %>
</div>

app/views/shared/_flash.html.erb
<% if flash[:notice] %>
  <div class="alert alert-info mt-4" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-warning mt-4" role="alert">
    <%= flash[:alert] %>
  </div>
<% end %>